/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ExternalBlob = Uint8Array;
export interface Log {
  'id' : LogId,
  'qty' : bigint,
  'remark' : string,
  'userName' : string,
  'userId' : string,
  'size' : string,
  'productId' : ProductId,
  'productName' : string,
  'logType' : LogType,
  'timestamp' : Timestamp,
  'hasBeenEdited' : boolean,
  'editedBy' : [] | [string],
}
export type LogId = bigint;
export type LogType = { 'IN' : null } |
  { 'OUT' : null };
export interface Product {
  'id' : bigint,
  'name' : string,
  'stock' : Array<[string, bigint]>,
  'availableSizes' : Array<string>,
  'image' : ExternalBlob,
  'colors' : Array<ProductColor>,
}
export interface ProductColor { 'name' : string, 'imageUrl' : string }
export type ProductId = bigint;
export interface SessionInfo {
  'userName' : string,
  'userId' : string,
  'role' : UserRole,
}
export interface SizeChange {
  'outQty' : bigint,
  'size' : string,
  'inQty' : bigint,
}
export type StockUpdateResult = { 'ok' : Product } |
  { 'err' : string };
export type Timestamp = bigint;
export interface UserPublic {
  'userName' : string,
  'userId' : string,
  'role' : UserRole,
}
export type UserRole = { 'admin' : null } |
  { 'owner' : null } |
  { 'user' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addProduct' : ActorMethod<
    [string, string, ExternalBlob, Array<string>, Array<[string, bigint]>],
    { 'ok' : Product } |
      { 'err' : string }
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'createNewUser' : ActorMethod<
    [string, string, string, string, string],
    { 'ok' : SessionInfo } |
      { 'err' : string }
  >,
  'deleteLog' : ActorMethod<
    [string, bigint],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getLogs' : ActorMethod<[], Array<Log>>,
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'getProducts' : ActorMethod<[], Array<Product>>,
  'getTotalProducts' : ActorMethod<[], bigint>,
  'getTotalStock' : ActorMethod<[], bigint>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAllUsers' : ActorMethod<
    [string],
    { 'ok' : Array<UserPublic> } |
      { 'err' : string }
  >,
  'login' : ActorMethod<[string, string], [] | [SessionInfo]>,
  'removeUser' : ActorMethod<
    [string, string],
    { 'ok' : null } |
      { 'err' : string }
  >,
  'seedUsers' : ActorMethod<[], undefined>,
  'updateLog' : ActorMethod<
    [bigint, string, string],
    { 'ok' : Log } |
      { 'err' : string }
  >,
  'updateProduct' : ActorMethod<
    [
      string,
      ProductId,
      [] | [string],
      [] | [ExternalBlob],
      [] | [Array<string>],
    ],
    { 'ok' : Product } |
      { 'err' : string }
  >,
  'updateStock' : ActorMethod<
    [ProductId, Array<SizeChange>, string, string, string],
    StockUpdateResult
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];