/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const ProductColor = IDL.Record({
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'stock' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'availableSizes' : IDL.Vec(IDL.Text),
  'image' : ExternalBlob,
  'colors' : IDL.Vec(ProductColor),
});
export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'owner' : IDL.Null,
  'user' : IDL.Null,
});
export const SessionInfo = IDL.Record({
  'userName' : IDL.Text,
  'userId' : IDL.Text,
  'role' : UserRole,
});
export const LogId = IDL.Nat;
export const ProductId = IDL.Nat;
export const LogType = IDL.Variant({ 'IN' : IDL.Null, 'OUT' : IDL.Null });
export const Timestamp = IDL.Int;
export const Log = IDL.Record({
  'id' : LogId,
  'qty' : IDL.Nat,
  'remark' : IDL.Text,
  'userName' : IDL.Text,
  'userId' : IDL.Text,
  'size' : IDL.Text,
  'productId' : ProductId,
  'productName' : IDL.Text,
  'logType' : LogType,
  'timestamp' : Timestamp,
  'hasBeenEdited' : IDL.Bool,
  'editedBy' : IDL.Opt(IDL.Text),
});
export const UserPublic = IDL.Record({
  'userName' : IDL.Text,
  'userId' : IDL.Text,
  'role' : UserRole,
});
export const SizeChange = IDL.Record({
  'outQty' : IDL.Nat,
  'size' : IDL.Text,
  'inQty' : IDL.Nat,
});
export const StockUpdateResult = IDL.Variant({
  'ok' : Product,
  'err' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        ExternalBlob,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
      ],
      [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'createNewUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : SessionInfo, 'err' : IDL.Text })],
      [],
    ),
  'deleteLog' : IDL.Func(
      [IDL.Text, IDL.Nat],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getLogs' : IDL.Func([], [IDL.Vec(Log)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getTotalProducts' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalStock' : IDL.Func([], [IDL.Nat], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAllUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Vec(UserPublic), 'err' : IDL.Text })],
      ['query'],
    ),
  'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(SessionInfo)], []),
  'removeUser' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
  'seedUsers' : IDL.Func([], [], []),
  'updateLog' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Log, 'err' : IDL.Text })],
      [],
    ),
  'updateProduct' : IDL.Func(
      [
        IDL.Text,
        ProductId,
        IDL.Opt(IDL.Text),
        IDL.Opt(ExternalBlob),
        IDL.Opt(IDL.Vec(IDL.Text)),
      ],
      [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
      [],
    ),
  'updateStock' : IDL.Func(
      [ProductId, IDL.Vec(SizeChange), IDL.Text, IDL.Text, IDL.Text],
      [StockUpdateResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const ProductColor = IDL.Record({ 'name' : IDL.Text, 'imageUrl' : IDL.Text });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'stock' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'availableSizes' : IDL.Vec(IDL.Text),
    'image' : ExternalBlob,
    'colors' : IDL.Vec(ProductColor),
  });
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'owner' : IDL.Null,
    'user' : IDL.Null,
  });
  const SessionInfo = IDL.Record({
    'userName' : IDL.Text,
    'userId' : IDL.Text,
    'role' : UserRole,
  });
  const LogId = IDL.Nat;
  const ProductId = IDL.Nat;
  const LogType = IDL.Variant({ 'IN' : IDL.Null, 'OUT' : IDL.Null });
  const Timestamp = IDL.Int;
  const Log = IDL.Record({
    'id' : LogId,
    'qty' : IDL.Nat,
    'remark' : IDL.Text,
    'userName' : IDL.Text,
    'userId' : IDL.Text,
    'size' : IDL.Text,
    'productId' : ProductId,
    'productName' : IDL.Text,
    'logType' : LogType,
    'timestamp' : Timestamp,
    'hasBeenEdited' : IDL.Bool,
    'editedBy' : IDL.Opt(IDL.Text),
  });
  const UserPublic = IDL.Record({
    'userName' : IDL.Text,
    'userId' : IDL.Text,
    'role' : UserRole,
  });
  const SizeChange = IDL.Record({
    'outQty' : IDL.Nat,
    'size' : IDL.Text,
    'inQty' : IDL.Nat,
  });
  const StockUpdateResult = IDL.Variant({ 'ok' : Product, 'err' : IDL.Text });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          ExternalBlob,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
        ],
        [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'createNewUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : SessionInfo, 'err' : IDL.Text })],
        [],
      ),
    'deleteLog' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getLogs' : IDL.Func([], [IDL.Vec(Log)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getTotalProducts' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalStock' : IDL.Func([], [IDL.Nat], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAllUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Vec(UserPublic), 'err' : IDL.Text })],
        ['query'],
      ),
    'login' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(SessionInfo)], []),
    'removeUser' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
    'seedUsers' : IDL.Func([], [], []),
    'updateLog' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Log, 'err' : IDL.Text })],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          IDL.Text,
          ProductId,
          IDL.Opt(IDL.Text),
          IDL.Opt(ExternalBlob),
          IDL.Opt(IDL.Vec(IDL.Text)),
        ],
        [IDL.Variant({ 'ok' : Product, 'err' : IDL.Text })],
        [],
      ),
    'updateStock' : IDL.Func(
        [ProductId, IDL.Vec(SizeChange), IDL.Text, IDL.Text, IDL.Text],
        [StockUpdateResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };